# Generated by Django 5.1.1 on 2024-09-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tki', '0002_tki_angkatan_tki_fakultas_tki_nim_tki_prodi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.CharField(max_length=255)),
                ('tki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tki.tki')),
            ],
        ),
    ]
